---
# - name: remove packages
#   tags:
#     - full-install
#     - light-install
#     - packages
#   package:
#     name:
#       - nodejs
#     state: absent
#     update_cache: no
#   become: true

- name: Change iptables to prevent conflict
  ansible.builtin.shell: yes | yay -S iptables-nft
  args:
    executable: /bin/bash

- name: Install kubernetes packages
  tags:
    - full-install
    - kubernetes
  kewlfft.aur.aur:
    name:
      - kubectl
      - kubectx
      - kubens
      - helm
      - docker-machine
      - docker-machine-driver-kvm2
      - minikube
      - lens-bin
    use: yay
    state: present
    update_cache: false

- name: get kubelogin
  shell: "cd {{ lookup('env', 'HOME') }}/.local/bin/ && wget -qO- https://github.com/Azure/kubelogin/releases/download/v0.0.29/kubelogin-linux-amd64.zip | bsdtar -xvf- --strip-components=2 bin/linux_amd64/kubelogin"
