- name: adding existing user erik to group docker
  user:
    name: erik
    groups: docker
    append: yes
  become: true

- name: adding existing user erik to group libvirt
  user:
    name: erik
    groups: libvirt
    append: yes
  become: true

- name: adding existing user erik to group audio
  user:
    name: erik
    groups: audio
    append: yes
  become: true

- name: adding existing user erik to group video
  user:
    name: erik
    groups: video
    append: yes
  become: true

- name: start bluetooth.service
  tags:
    - full-install
    - users
  ansible.builtin.service:
    name: bluetooth.service
    state: started
    enabled: yes
  become: true

- name: start cups.service
  tags:
    - full-install
    - users
  ansible.builtin.service:
    name: cups.service
    state: started
    enabled: yes
  become: true

- name: start sddm.service
  tags:
    - full-install
    - users
  ansible.builtin.service:
    name: sddm.service
    state: started
    enabled: yes
  become: true

- name: copy networkmanager config files
  tags:
    - full-install
    - users
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: "networkmanager/", dest: "/etc/NetworkManager/conf.d" }

- name: start NetworkManager.service
  tags:
    - full-install
    - users
  ansible.builtin.service:
    name: NetworkManager.service
    state: started
    enabled: yes
  become: true
