format = """
[ ](#ff79c6) \
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$nodejs\
$cmd_duration $jobs $time\
$line_break\
$character"""

[nodejs]
format = "[$symbol($version )]($style)"

[fill]
symbol = " "

[directory]
style = "bold #50fa7b"
read_only = " "
truncation_length = 3
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold #ff79c6"

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold #ff5555"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[hostname]
style = "bold #ff5555"
ssh_only = false

[username]
show_always = true
disabled = false
format = " [$user]($style) on "
style_user = "bold #bd93f9"

[cmd_duration]
format = "[$duration]($style)"
style = "bold #f1fa8c"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "bold"

[custom.stunnel]
when = "ps aux | grep stunnel | grep -v grep"
command = "ps -o etime= -p $(ps aux | grep stunnel | grep -v grep | awk '{print $2}')"
style = "red"
format = "[TUNNEL OPEN for $output]($style)"